### ISSUE TITLE
Optimize the documentation and the getting started guide

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/ImageGoNord#34]
- getting started
- how to install the pip package
- show some code examples
- api documentation to run on a private server
- heroku api documentation
- cli documentation
- troubleshooting

**Comment by Wabri** [comment]
@ffex are you still working on it? I will remove the assignment if not!

**Comment by akaashvaa** [comment]
@Wabri can i work on this issue ?  maybe i will ask too questions because i'm new to open source  .

_show some code examples
api documentation to run on a private server
cli documentation
troubleshooting_

### for these headings where can i get to know more about this term and details so i can make sure to prepare myself for better documentation .

**Comment by akaashvaa** [comment]
@Wabri  thankuu , can u please send me the discord link ?

> Hi @akaashvaa, of course you can. Right now this project is in a stalemate, but we are considering on getting back into it.
> 
> If you have any question, just ping us here or in the discord server.

thankuu , can u please drop the discord link ?

**Comment by TheJoin95** [comment]
@akaashvaa https://discord.gg/RTXr8A3eFn

**Comment by akaashvaa** [comment]
$ vue-cli-service serve
 INFO  Starting development server...
  0% compilingℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/aksh/ImageGoNord/src/ign-frontend/public
ℹ ｢wds｣: 404s will fallback to /index.html
/home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js:206
        compilation.hooks.processAssets.tap(
                                        ^

TypeError: Cannot read properties of undefined (reading 'tap')
    at /home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js:206:41
    at SyncHook.eval [as call] (eval at create (/home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:19:1)
    at SyncHook.lazyCompileHook (/home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:507:26)
    at /home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:543:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:538:28)
    at /home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/webpack/lib/Watching.js:76:18
    at _next0 (eval at create (/home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at eval (eval at create (/home/aksh/ImageGoNord/src/ign-frontend/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:36:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

#### i have tried many times , upgrading packages nand all but i get this isuue . any suggestion ?
